services:
  directus:
    image: docker.io/directus/directus:11@sha256:076269ccbe7d4a0c44ce5f5b7f11e2ea5f7b3e4c4f704c0f88a52805e069c1c6
    ports:
      - 8055:8055
    volumes:
      - database:/directus/database
      - uploads:/directus/uploads
      - .:/directus/extensions/directus-extension-blurhasher
      - .:/directus/node_modules/directus-extension-blurhasher
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: 10000

volumes:
  database:
  uploads:
