# Dependency age
minimumReleaseAge: 4320 # 3 days - same as renovate
minimumReleaseAgeExclude:
    - "@foldland/*"
    # security issues
    - js-yaml@4.3.0
    - axios@1.18.0
    - sharp@0.35.0

registries:
    default: https://registry.npmjs.org/
    "@foldland": https://npm.registry.foldland.io

# Dependency resolution
savePrefix: "^"
resolutionMode: "highest"
strictPeerDependencies: true
preferFrozenLockfile: true

# node version
engineStrict: true
ignorePnpmfile: true
# pnpm version
packageManagerStrict: true
packageManagerStrictVersion: true

# Security
blockExoticSubdeps: true
hoist: false
hoistWorkspacePackages: false
verifyDepsBeforeRun: "install"

# avoid including the linked extension
packages:
    - "!directus/**"

overrides:
    # broken directus peers
    "@vitejs/plugin-vue@6.0.1": ^6.0.3
    # security issues
    axios@>=1.15.2 <1.18.0: ^1.18.0
    js-yaml@>=4.0.0 <4.3.0: ^4.3.0
    sharp@<0.35.0: ^0.35.0

allowBuilds:
    esbuild: false
    sharp: false
    vue-demi: false
