name: directus-nextjs-blurhash
services:
    database:
        image: docker.io/postgis/postgis:18-master@sha256:b714e6e8f6f2e891e7cc676722f3f2873cb36c6e695ac94335698792069ef8fb
        platform: linux/amd64
        volumes:
            - ${DATABASE_VOLUME:-./data/database}:/var/lib/postgresql
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        healthcheck:
            test:
                [
                    "CMD",
                    "pg_isready",
                    "-U",
                    "${DB_USER}",
                    "-d",
                    "${DB_DATABASE}",
                    "-h",
                    "localhost",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_interval: 5s
            start_period: 30s

    cache:
        image: docker.io/redis:8@sha256:2838d5524559494f6f1cd66e97e76b200d64a633a8614200620755ed395daf32
        healthcheck:
            test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_interval: 5s
            start_period: 30s

    directus:
        image: docker.io/directus/directus:12.0@sha256:9c8470ea465cb78ff902221847f73c8516dadeff40b02fcb195065745e9d7874
        # build:
        #     context: ../
        #     dockerfile: ./Dockerfile
        ports:
            - ${DIRECTUS_PORT}:8055
        volumes:
            - ${UPLOADS_VOLUME:-./uploads}:/directus/uploads
            - ${EXTENSIONS_VOLUME:-./extensions}:/directus/extensions
            # Local extension development
            - ../:/directus/extensions/@foldland-directus-nextjs-blurhash
        depends_on:
            database:
                condition: service_healthy
            cache:
                condition: service_healthy
        env_file:
            - .env
        environment:
            SECRET: ${DIRECTUS_SECRET}

            DB_CLIENT: "pg"
            DB_HOST: "database"
            DB_PORT: "5432"

            CACHE_STORE: "redis"
            REDIS: "redis://cache:6379"
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    extensions:
    uploads:
    database:
