import type { FieldMeta } from '@directus/types'

export const blurhash = {
  collection: 'directus_files',
  field: 'blurhash',
  type: 'string',
  meta: {
    collection: 'directus_files',
    conditions: null,
    display: null,
    display_options: null,
    field: 'blurhash',
    group: null,
    hidden: false,
    interface: 'input',
    note: 'Automatically generated by the nextjs-blurhash extension',
    options: null,
    readonly: true,
    required: false,
    searchable: false,
    sort: 1,
    special: null,
    translations: null,
    validation: null,
    validation_message: null,
    width: 'full',
  } as FieldMeta,
  schema: {
    name: 'blurhash',
    table: 'directus_files',
    data_type: 'character varying',
    default_value: null,
    max_length: 3000,
    numeric_precision: null,
    numeric_scale: null,
    is_nullable: true,
    is_unique: false,
    is_indexed: false,
    is_primary_key: false,
    is_generated: false,
    generation_expression: null,
    has_auto_increment: false,
    foreign_key_table: null,
    foreign_key_column: null,
  },
} as const

/**
 * Height of the output image.
 *
 * Output images are always scaled, keeping their aspect ratio.
 */
export const blurSize = {
  collection: 'directus_settings',
  field: 'blurhasher_blur_size',
  type: 'integer',
  meta: {
    collection: 'directus_settings',
    conditions: null,
    display: null,
    display_options: null,
    field: 'blurhasher_blur_size',
    group: null,
    hidden: false,
    interface: 'input',
    note: 'Height of the output image. Output images are always scaled, keeping their aspect ratio.',
    options: null,
    readonly: false,
    required: true,
    searchable: true,
    sort: 1,
    special: null,
    translations: null,
    validation: null,
    validation_message: null,
    width: 'half',
  } as FieldMeta,
  schema: {
    name: 'blurhasher_blur_size',
    table: 'directus_settings',
    data_type: 'integer',
    default_value: 8,
    max_length: null,
    numeric_precision: 32,
    numeric_scale: 0,
    is_nullable: false,
    is_unique: false,
    is_indexed: false,
    is_primary_key: false,
    is_generated: false,
    generation_expression: null,
    has_auto_increment: false,
    foreign_key_table: null,
    foreign_key_column: null,
  },
} as const

/**
 * Format of the output image (blur)
 * Benchmark sample size: 1
 *
 * |      | 8px | 5px |
 * |------|-----|-----|
 * | jpeg | 432 | 408 |
 * | png  | 516 | 268 |
 * | webp | 128 | 108 |
 * | avif | 396 | 380 |
 */
export const format = {
  collection: 'directus_settings',
  field: 'blurhasher_format',
  type: 'string',
  meta: {
    collection: 'directus_settings',
    conditions: null,
    display: null,
    display_options: null,
    field: 'blurhasher_format',
    group: null,
    hidden: false,
    interface: 'select-dropdown',
    note: 'Format of the output image (blur)',
    options: {
      allowNone: true,
      choices: [
        {
          text: 'jpeg',
          value: 'jpeg',
        },
        {
          text: 'png',
          value: 'png',
        },
        {
          text: 'webp',
          value: 'webp',
        },
        {
          text: 'avif',
          value: 'avif',
        },
      ],
    },
    readonly: false,
    required: true,
    searchable: true,
    sort: 2,
    special: null,
    translations: null,
    validation: null,
    validation_message: null,
    width: 'half',
  } as unknown as FieldMeta,
  schema: {
    name: 'blurhasher_format',
    table: 'directus_settings',
    data_type: 'character varying',
    default_value: 'webp',
    max_length: 255,
    numeric_precision: null,
    numeric_scale: null,
    is_nullable: false,
    is_unique: false,
    is_indexed: false,
    is_primary_key: false,
    is_generated: false,
    generation_expression: null,
    has_auto_increment: false,
    foreign_key_table: null,
    foreign_key_column: null,
  },
} as const

/**
 * Chunks size for batch blur generation.
 *
 * Used on on start when images have no blurData or regenerate is enabled.
 */
export const generationChunkSize = {
  collection: 'directus_settings',
  field: 'blurhasher_generation_chunk_size',
  type: 'integer',
  meta: {
    collection: 'directus_settings',
    conditions: null,
    display: null,
    display_options: null,
    field: 'blurhasher_generation_chunk_size',
    group: null,
    hidden: false,
    interface: 'input',
    note: 'Chunks size for batch blur generation. Used on on start when images have no blurData or regenerate is enabled.',
    options: null,
    readonly: false,
    required: true,
    searchable: true,
    sort: 3,
    special: null,
    translations: null,
    validation: null,
    validation_message: null,
    width: 'full',
  } as FieldMeta,
  schema: {
    name: 'blurhasher_generation_chunk_size',
    table: 'directus_settings',
    data_type: 'integer',
    default_value: 4,
    max_length: null,
    numeric_precision: 32,
    numeric_scale: 0,
    is_nullable: false,
    is_unique: false,
    is_indexed: false,
    is_primary_key: false,
    is_generated: false,
    generation_expression: null,
    has_auto_increment: false,
    foreign_key_table: null,
    foreign_key_column: null,
  },
} as const

/**
 * Force regenerates all images on start.
 */
export const regenerateOnStart = {
  collection: 'directus_settings',
  field: 'blurhasher_regenerate_on_start',
  type: 'boolean',
  meta: {
    collection: 'directus_settings',
    conditions: null,
    display: null,
    display_options: null,
    field: 'blurhasher_regenerate_on_start',
    group: null,
    hidden: false,
    interface: 'boolean',
    note: 'Force regenerates all images on start.',
    options: null,
    readonly: false,
    required: true,
    searchable: true,
    sort: 4,
    special: ['cast-boolean'],
    translations: null,
    validation: null,
    validation_message: null,
    width: 'half',
  } as FieldMeta,
  schema: {
    name: 'blurhasher_regenerate_on_start',
    table: 'directus_settings',
    data_type: 'boolean',
    default_value: false,
    max_length: null,
    numeric_precision: null,
    numeric_scale: null,
    is_nullable: false,
    is_unique: false,
    is_indexed: false,
    is_primary_key: false,
    is_generated: false,
    generation_expression: null,
    has_auto_increment: false,
    foreign_key_table: null,
    foreign_key_column: null,
  },
} as const

/**
 * Generate blur data when missing.
 */
export const generateMissingOnStart = {
  collection: 'directus_settings',
  field: 'blurhasher_generate_missing_on_start',
  type: 'boolean',
  meta: {
    collection: 'directus_settings',
    conditions: null,
    display: null,
    display_options: null,
    field: 'blurhasher_generate_missing_on_start',
    group: null,
    hidden: false,
    interface: 'boolean',
    note: 'Generate blur data when missing.',
    options: null,
    readonly: false,
    required: true,
    searchable: true,
    sort: 5,
    special: ['cast-boolean'],
    translations: null,
    validation: null,
    validation_message: null,
    width: 'half',
  } as FieldMeta,
  schema: {
    name: 'blurhasher_generate_missing_on_start',
    table: 'directus_settings',
    data_type: 'boolean',
    default_value: true,
    max_length: null,
    numeric_precision: null,
    numeric_scale: null,
    is_nullable: false,
    is_unique: false,
    is_indexed: false,
    is_primary_key: false,
    is_generated: false,
    generation_expression: null,
    has_auto_increment: false,
    foreign_key_table: null,
    foreign_key_column: null,
  },
} as const
