import type { AbstractService, Field, Type } from '@directus/types'
import type { DirectusSettings } from '@/utils/directus-schema.ts'
import type { FieldsService } from './types.ts'

const directus_files_blurhash = {
  collection: 'directus_files',
  field: 'blurhash',
  type: 'string',
  meta: {
    id: Number.NaN,
    searchable: false,
    collection: 'directus_files',
    field: 'blurhash',
    special: null,
    interface: 'input',
    options: null,
    display: null,
    display_options: null,
    readonly: false,
    hidden: false,
    sort: 1,
    width: 'full',
    translations: null,
    note: 'Automatically generated by the nextjs-blurhash extension',
    conditions: null,
    required: false,
    group: null,
    validation: null,
    validation_message: null,
  },
  schema: {
    name: 'blurhash',
    table: 'directus_files',
    data_type: 'varchar',
    default_value: null,
    max_length: 3000,
    numeric_precision: null,
    numeric_scale: null,
    is_generated: false,
    generation_expression: null,
    is_nullable: true,
    is_unique: false,
    is_primary_key: false,
    has_auto_increment: false,
    foreign_key_column: null,
    foreign_key_table: null,
    is_indexed: false,
  },
} as const

const settings_detail_level = {
  collection: 'directus_settings',
  field: 'blurhasher_detail_level',
  type: 'string',
  meta: {
    id: Number.NaN,
    searchable: false,
    collection: 'directus_settings',
    field: 'blurhasher_detail_level',
    special: null,
    interface: 'select-dropdown',
    options: {
      choices: [
        { text: 'High', value: 'high' },
        { text: 'Medium', value: 'medium' },
        { text: 'Low', value: 'low' },
      ],
    },
    display: null,
    display_options: null,
    readonly: false,
    hidden: false,
    sort: 1,
    width: 'full',
    translations: null,
    note: 'This parameter determines the detail level in the BlurHash, affecting its complexity and length from high (detailed) to low (abstract).',
    conditions: null,
    required: false,
    group: null,
    validation: null,
    validation_message: null,
  },
  schema: {
    name: 'blurhasher_detail_level',
    table: 'directus_settings',
    data_type: 'varchar',
    default_value: 'medium',
    max_length: 255,
    numeric_precision: null,
    numeric_scale: null,
    is_generated: false,
    generation_expression: null,
    is_nullable: true,
    is_unique: false,
    is_primary_key: false,
    has_auto_increment: false,
    foreign_key_column: null,
    foreign_key_table: null,
    is_indexed: false,
  },
} as const

const settings_regenerate = {
  collection: 'directus_settings',
  field: 'blurhasher_regenerate_on_restart',
  type: 'boolean',
  meta: {
    id: Number.NaN,
    searchable: false,
    collection: 'directus_settings',
    field: 'blurhasher_regenerate_on_restart',
    special: ['cast-boolean'] as Array<string>,
    interface: 'boolean',
    options: null,
    display: null,
    display_options: null,
    readonly: false,
    hidden: false,
    sort: 2,
    width: 'full',
    translations: null,
    note: 'Enables regeneration of all BlurHashes for illustrations upon system restart.',
    conditions: null,
    required: false,
    group: null,
    validation: null,
    validation_message: null,
  },
  schema: {
    name: 'blurhasher_regenerate_on_restart',
    table: 'directus_settings',
    data_type: 'boolean',
    default_value: false,
    max_length: null,
    numeric_precision: null,
    numeric_scale: null,
    is_generated: false,
    generation_expression: null,
    is_nullable: true,
    is_unique: false,
    is_primary_key: false,
    has_auto_increment: false,
    foreign_key_column: null,
    foreign_key_table: null,
    is_indexed: false,
  },
} as const

const settingsFields = {
  detail_level: settings_detail_level.field,
  regenerate: settings_regenerate.field,
}

/**
 * Ensures the existence of a field in Directus.
 * If the field does not exist, it creates the field using the provided field configuration.
 *
 * @param fieldsService - The Directus fields service.
 * @param field - The field configuration to ensure.
 * @param logger - The logger instance for logging messages.
 */
async function ensureField(
  fieldsService: FieldsService,
  field: Partial<Field> & {
    collection: string
    field: string
    type: Type | null
  }
): Promise<void> {
  const found = await fieldsService
    .readOne(field.collection, field.field)
    .catch(() => {
      return undefined
    })

  if (found) {
    return
  }

  await fieldsService.createField(field.collection, field)
}

/**
 * Runs the migration process.
 *
 * @param fieldsService - The service for managing fields.
 * @param logger - The logger for logging messages.
 */
export async function runMigration(fieldsService: FieldsService) {
  await ensureField(fieldsService, directus_files_blurhash)
  await ensureField(fieldsService, settings_detail_level)
  await ensureField(fieldsService, settings_regenerate)
}

/**
 * Retrieves a setting value from a service.
 * @param service - The service to retrieve the setting from.
 * @param field - The name of the setting field.
 * @param logger - Logger instance for logging progress and errors.
 * @returns The value of the setting, or null if not found.
 */
export async function getSetting(
  service: AbstractService<DirectusSettings>,
  field: 'detail_level' | 'regenerate'
): Promise<unknown | null> {
  try {
    const setting = settingsFields[field]

    const found = await service.readSingleton({ fields: [setting] })
    return found[setting]
  } catch {
    return null
  }
}
